[env:esp32-evb]
platform = espressif32
board = esp32-evb
framework = arduino
monitor_speed = 115200

; Library dependencies
lib_deps = 
    knolleary/PubSubClient@^2.8
    arduino-libraries/NTPClient@^3.2.1
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.8
    bblanchon/ArduinoJson@^6.21.2  ; If you need JSON parsing
    me-no-dev/AsyncTCP@^1.1.1
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    akj7/TM1637 Driver@^2.2.1

; Build flags for optimization and debug
build_flags = 
    ; Debug flags
    -DCORE_DEBUG_LEVEL=5
    -DDEBUG_ESP_SSL
    -DDEBUG_ESP_PORT=Serial

    ; Reduce SSL buffer sizes
    -DMBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DMBEDTLS_SSL_OUT_CONTENT_LEN=4096
    -DMQTT_MAX_PACKET_SIZE=1024

    ; TCP configurations
    -DCONFIG_LWIP_TCP_MSS=1436
    -DCONFIG_LWIP_TCP_WND=5744
    -DCONFIG_LWIP_MAX_SOCKETS=8
    -DCONFIG_LWIP_SO_RCVBUF=1
    
    ; Aggressive keepalive
    -DCONFIG_LWIP_TCP_KEEPALIVE=1
    -DCONFIG_TCP_KEEPIDLE=30
    -DCONFIG_TCP_KEEPINTVL=15
    -DCONFIG_TCP_KEEPCNT=5

    ; Additional TCP configurations
    -DCONFIG_LWIP_TCP_SYNMAXRTX=6
    -DCONFIG_LWIP_TCP_MSL=60000
    -DLWIP_DEBUG=1
    -DLWIP_DEBUG_LEVEL=LWIP_DBG_LEVEL_ALL

